CREATE DATABASE `lbs`
CREATE TABLE `lib` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `BOOK` varchar(50) NOT NULL,
  `AUTHOR` varchar(50) NOT NULL,
  `STATUS` enum('borrowed','available') DEFAULT 'available',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `BOOK_UNIQUE` (`BOOK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
CREATE TABLE `students` (
  `ROLL` int NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `CLASS` varchar(45) NOT NULL,
  `BOOK` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLL`),
  UNIQUE KEY `ROLL_UNIQUE` (`ROLL`),
  UNIQUE KEY `BOOK_UNIQUE` (`BOOK`),
  CONSTRAINT `fk_book` FOREIGN KEY (`BOOK`) REFERENCES `lib` (`BOOK`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
